Repository DO-SOPT-SOPKATHON-iOS4/SOPKATHON-iOS, pull requests merged in 2023-11, with the labels that each got.

#3 [Setting] #2 - 프로젝트 세팅
  SOPKATHON-iOS/SOPKATHON-iOS.xcodeproj/project.pbxproj
  SOPKATHON-iOS/SOPKATHON-iOS/Application/SceneDelegate.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Extension/NSObject+.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Extension/UIColor+.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Extension/UIStackView+.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Extension/UIView+.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Literals/ColorLiterals.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Literals/FontLiterals.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Protocols/UICollectionViewRegisterable.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Protocols/UITableViewRegisterable.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Network/Base/BaseService.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Network/Base/GenericResponse.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Network/Base/NetworkConstant.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Network/Base/NetworkResult.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Network/Base/URLConstant.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Network/Config/Config.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/Example/View/ExampleView.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/Example/ViewController/ViewController.swift
Labels: 🦖아라, 👩🏻‍💻Feat

#11 [Feature] #8 - 히스토리 뷰 UI 구현
  SOPKATHON-iOS/SOPKATHON-iOS.xcodeproj/project.pbxproj
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/Q1_ic_left_arrow.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/Q1_ic_left_arrow.imageset/Q1_ic_left_arrow.svg
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/level1.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/level1.imageset/level1.svg
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/HistoryScene/Cell/HistoryCollectionViewCell.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/HistoryScene/View/HistoryView.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/HistoryScene/ViewController/HistoryViewController.swift
Labels: 😻희슬, 👩🏻‍💻Feat

#15 [Setting] 이미지 세팅
  SOPKATHON-iOS/SOPKATHON-iOS.xcodeproj/project.pbxproj
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Literals/ImageLiterals.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/QA_OX_btn_O.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/QA_OX_btn_O.imageset/QA_OX_btn_O.svg
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/QA_OX_btn_X.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/QA_OX_btn_X.imageset/QA_OX_btn_X.svg
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/go_to_history.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/go_to_history.imageset/go_to_history.svg
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/go_to_question.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/go_to_question.imageset/go_to_question.svg
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/level2.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/level2.imageset/level2.svg
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/level3.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/level3.imageset/level3.svg
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/level4.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/level4.imageset/level4.svg
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/level5.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/level5.imageset/level5.svg
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/onboarding_character.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/onboarding_character.imageset/onboarding.svg
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/result1.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/result1.imageset/result1.svg
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/result2.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/result2.imageset/result2.svg
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/result3.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/result3.imageset/result3.svg
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/result4.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/result4.imageset/result4.svg
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/result5.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/result5.imageset/result5.svg
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/splash_character.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/splash_character.imageset/splash_character_10.svg
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/splash_graphic_background.imageset/Contents.json
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Assets.xcassets/splash_graphic_background.imageset/splash_graphic_background.svg
Labels: 😻희슬, ⚙️Setting

#16 [Setting] #13 폰트, 컬러 세팅 추가
  SOPKATHON-iOS/SOPKATHON-iOS.xcodeproj/project.pbxproj
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Literals/ColorLiterals.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Literals/FontLiterals.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Fonts/Pretendard-Bold.otf
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Fonts/Pretendard-Regular.otf
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Fonts/Pretendard-SemiBold.otf
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Resources/Fonts/chab.otf
  SOPKATHON-iOS/SOPKATHON-iOS/Info.plist
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/Example/View/ExampleView.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/MainScene/View/MainView.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/MainScene/ViewController/MainViewController.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/OnboardingScene/View/OnboardingNicknameView.swift
Labels: 🐢상우, ⚙️Setting

#22 [Setting] #19 서버 세팅 완료
  SOPKATHON-iOS/SOPKATHON-iOS.xcodeproj/project.pbxproj
  SOPKATHON-iOS/SOPKATHON-iOS/Info.plist
Labels: 🐢상우, ⚙️Setting

#23 [Feat] 히스토리 뷰 에셋 적용
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/HistoryScene/Cell/HistoryCollectionViewCell.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/HistoryScene/View/HistoryView.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/HistoryScene/ViewController/HistoryViewController.swift
Labels: 😻희슬, 👩🏻‍💻Feat

#27 [Feat] 스플래시 화면 구현
  SOPKATHON-iOS/SOPKATHON-iOS.xcodeproj/project.pbxproj
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/OnboardingScene/View/OnboardingNicknameView.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/SplashScene/View/SplashView.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/SplashScene/ViewController/SplashViewController.swift
Labels: 😻희슬, 👩🏻‍💻Feat

#29 [Feat] 히스토리뷰 서버 통신
  SOPKATHON-iOS/SOPKATHON-iOS.xcodeproj/project.pbxproj
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Literals/ColorLiterals.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Protocols/GetHistoryDataProtocol.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Network/Entity/GetHistoryEntity.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Network/Services/GetHistoryService.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/HistoryScene/Cell/HistoryCollectionViewCell.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/HistoryScene/View/HistoryView.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/HistoryScene/ViewController/HistoryViewController.swift
Labels: 😻희슬, 👩🏻‍💻Feat

#32 [Feat] #18 온보딩뷰, 홈뷰 디자인 완료, 서버 API 연결 구현
  SOPKATHON-iOS/SOPKATHON-iOS.xcodeproj/project.pbxproj
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Extension/UINavigationController+.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Global/Extension/UIViewController+.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Network/Entity/OnboardingEntity.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Network/Services/OnboardingService.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/MainScene/View/MainHistoryView.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/MainScene/View/MainLaunchScreenView.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/MainScene/View/MainStartQuestionView.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/MainScene/View/MainView.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/MainScene/ViewController/MainViewController.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/OnboardingScene/View/OnboardingAgeView.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/OnboardingScene/View/OnboardingNicknameView.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/OnboardingScene/ViewController/OnboardingAgeViewController.swift
  SOPKATHON-iOS/SOPKATHON-iOS/Presentation/OnboardingScene/ViewController/OnboardingNicknameViewController.swift
Labels: 🐢상우, 👩🏻‍💻Feat
